

export const products = [
  {
    id: 1,
    nombre: "Nike V2K Run",
    precio: 119.99,
    img:src = "./public/images/01v2k-run-zapatillas-ZzTJRD.jpg",
    specialType: "Materiales Sostenibles", 
    modelNike: "Run",
    nroColores: "5 colores",
    colores: [ "#F9FAFF", "#8e9297", "#6a665a","#bfd98e","black"],
  },
  {
    id: 2,
    nombre: "Nike Dunk Low",
    precio: 119.99,
    img: src ="./public/images/02dunk-low-zapatillas-15mQNw.jpg",
    specialType: "Superventas", 
    modelNike: "Dunk Low",
    nroColores: "6 colores",
    colores: ["#F9FAFF","#6da4e6", "red",  "green","#6a665a","black"],
  },
  {
    id: 3,
    nombre: "Nike Air Force 1 `07 nature",
    precio: 119.99,
    img: src = "./public/images/03air-force-1-07-next-nature-zapatillas-dgr2tk.jpg",
    specialType: "Superventas",
    modelNike: "Air Force 1",
    nroColores: "5 colores",
    colores: ["#F9FAFF", "#6da4e6", "red","#8e9297", "#6a665a" ],
  },
  {
    id: 4,
    nombre: "Nike Air Max Pulse",
    precio: 79.97,
    img: src ="./public/images/04air-max-pulse-zapatillas-lgFPkM.jpg",
    specialType: "New",
    modelNike: "Run",
    nroColores: "5 colores",
    colores: ["#F9FAFF", "#bfd98e", "#6da4e6", "#8d60bf","#8e9297"],
  },
  {
    id: 5,
    nombre: "Nike Cortez",
    specialType: "Un Clasico Renovado",
    img: src ="./public/images/05prop.jpg",
    modelNike: "Nike Cortez",
    precio: 159.99,
    colores: ["#F9FAFF"],
  },
  {
    id: 6,
    nombre: "Nike Air Force 1 `07 Lx",
    precio: 129.99,
    img: src ="./public/images/06air-force-1-07-lx-zapatillas-bRRHxR.jpg",
    specialType: "Superventas",
    modelNike: "Air Force 1",
    nroColores: "1 color",
    colores: ["#F9FAFF"],
  },
  {
    id: 7,
    nombre: "Nike Jordan 1 Low",
    precio: 129.99,
    img: src ="./public/images/07air-jordan-1-low-zapatillas-QnthX1.jpg",
    specialType: "Materiales Sostenibles",
    modelNike: "Air Jordan",
    nroColores: "6 colores",
    colores: [ "#F9FAFF","#6da4e6","red", "#f7b64e", "#8e9297","black"],
  },
  {
    id: 8,
    nombre: "Nike Phoenix Waffle",
    precio: 99.99,
    img: src ="./public/images/08phoenix-waffle-zapatillas-DTQ3JT.jpg",
    specialType: "New",
    modelNike: "Waffle",
    nroColores: "4 colores",
    colores: [ "#F9FAFF","#6da4e6","#bfd98e","#6a665a"],
  },
  {
    id: 9,
    nombre: "Nike Court Legacy Lift",
    precio: 99.27,
    img: src ="./public/images/10air-jordan-1-low-se-zapatillas-RRW0nZ.jpg",
    specialType: "Superventas",
    nroColores: "4 colores",
    modelNike: "Court Legacy",
    colores: ["#F9FAFF", "#f7b64e","#bfd98e","black"],
  },
  {
    id: 10,
    nombre: "Nike Jordan 1 Low SE",
    precio: 119.99,
    img: src ="./public/images/11air-max-97-zapatillas-frVmb5.jpg",
    specialType: "Materiales Sostenibles", 
    modelNike: "Air Jordan",
    nroColores: "3 colores",
    colores: [ "#F9FAFF", "#8e9297","black"],
  },
  {
    id: 11,
    nombre: "Nike Air max 97",
    precio: 94.99,
    img: src = "./public/images/12air-jordan-1-mid-zapatillas-CR2SZ7.jpg",
    specialType: "New", 
    modelNike: "Air Jordan",
    nroColores: "2 colores",
    colores: ["#F9FAFF","black",],
  },
  {
    id: 12,
    nombre: "Air Jordan 1 Mid",
    precio: 159.99,
    img: src ="./public/images/03air-force-1-07-next-nature-zapatillas-dgr2tk.jpg",
    specialType: "Superventas",
    modelNike: "Air Jordan",
    nroColores: "2 colores",
    colores: [   "#F9FAFF", "black", ],
  }
];
